name: CommandStands
main: net.orendigo.commandstands.CommandStands
version: '1.5 (1.16.2)'
author: Orendigo
api-version: 1.16
description: Edit armour stands using commands
softdepend: [WorldGuard, WorldEdit, ProtocolLib]

commands:
    as:
        description: CommandStands main command
        permission: as.use

permissions:
    as.use:
        description: gives access to all basic features of CommandStands
        default: true
    as.clone:
        description: gives access to /as clone
        default: op

